version: "3.8"

services:
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"

  etl-flow:
    build:
      context: .
      dockerfile: Dockerfile.flow
    depends_on:
      - prefect-server
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    volumes:
      - spacex-data:/app/data

  streamlit-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8501:8501"
    depends_on:
      - etl-flow
    volumes:
      - spacex-data:/app/data

volumes:
  spacex-data: