[project]
name = "SpaceX-Insights"
version = "0.1.0"
description = "Extracting data from the official SpaceX API and analyze the data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
